### ISSUE TITLE
[Error] mkdir: cannot create directory: Permission denied

### ISSUE THREAD

**Issue by SolAZDev** [kamildzi/Tizen4Docker#12]
Good Afternoon;I'm running into the issue state on the title. I'm running Manjaro KDE with docker 19.03. I'm _almost_ certain I might've missed something, I'm honestly pretty new to docker; but as II have followed the [Arch Wiki for Docker](https://wiki.archlinux.org/index.php/Docker).
This occurs regardless of running with privileges or run as a normal user (albeit being part of the docker group). 

Log
``` [./runTizen.sh] Starting up ...
non-network local connections being added to access control list
mkdir: cannot create directory '~/tizen-studio-data/_EXT_TIZEN4DOCKER_': Permission denied
GNOME_KEYRING_CONTROL=~/.cache/keyring-JR0WK0
SSH_AUTH_SOCK=~/.cache/keyring-JR0WK0/ssh
bash: line 4: ~/tizen-studio/ide/TizenStudio.sh: No such file or directory
 [./runTizen.sh] Terminating ...
non-network local connections being removed from access control list
```

**Comment by kamildzi** [comment]
Hello, 

Thank you for opening an issue. 
Actually this is related to two sub-issues. 
Let us split it into two cases.

# case 1
There was a little bug preventing a fresh IDE installation from being completed. I have just fixed this. 
Please update Tizen4Docker by pulling the latest version from the master branch. 
**Note:** you will need to rebuild (or remove) your current docker image. 

# case 2
It looks to me like you are having some permissions issues here: 
```
mkdir: cannot create directory '~/tizen-studio-data/_EXT_TIZEN4DOCKER_': Permission denied
```
You should definitely fix this. Latest Tizen4Docker version won't let you proceed if this is not fixed. 
- Please make sure that your user has full (755) permissions to paths which are used in the `.env` file: `LOCAL_WORKSPACE`, `LOCAL_TIZEN_STUDIO_DIRECTORY`, and `LOCAL_TIZEN_STUDIO_DATA_DIRECTORY`. 
You need to be able to read and write data to each of these directories. 
- Please run `id` command and make sure that your `username`, `uid` and `gid` matches values set in your `.env` file: `TIZEN_USER`, `TIZEN_UID` and `TIZEN_GID`. 

If you are still getting 'Permission denied' error, please post your `.env` file. I will try to reproduce this error.

**Comment by SolAZDev** [comment]
It was unsurprisingly, a permission error; I had to `chown && chmod 755` the correct directories, after this it worked fine after installing their packages. Thank you so much for the help and quick response!

**Comment by kamildzi** [comment]
You are welcome. Glad I could help. :)
