### ISSUE TITLE
Emulator Manager + Device Manager not loading

### ISSUE THREAD

**Issue by samcday** [kamildzi/Tizen4Docker#18]
Trying to launch either Emulator or Device Managers from Tizen Studio does nothing.

I then tried attaching a shell to the running container (`docker exec -it <container id> bash`) and running the emulator manager directly (`~/tizen-studio/tools/emulator/bin/emulator-manager`), which yielded the following output:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
```

I'm guessing maybe something is up with my host X11 config? I'm running stock Ubuntu 20.04 LTS with the Nvidia proprietary drivers on a RTX 2060.

**Comment by samcday** [comment]
What's interesting is I can run the emulator manager directly (outside of the Docker environment) and it boots up. It then freaks out because paths are mismatched between the Docker environment and the host - but that's irrelevant. So maybe something up with the way X11 is passed through to the container?

**Comment by kamildzi** [comment]
Hello, 

If the main IDE window starts up when you use `runTizen.sh` script, then I believe that your X11 configuration is fine. 

I have installed Ubuntu 20.04 inside VirtualBox, hoping that I will be able to reproduce the issue. 
Unfortunately I wasn't able to reproduce this. Installation inside VM went fine and the problem didn't occurred for me. 

I am not really sure what might be causing the issue, but I think that I have found something interesting. 
Please check out following issue, it seems to be related to your problem: 
https://github.com/SoonminHwang/dockers/issues/1

It seems like Nvidia drivers require some additional libraries to be shared with the docker container. 
Solution above is to use docker volumes: 
![obraz](https://user-images.githubusercontent.com/12057520/90324408-c6078680-df6e-11ea-885c-7797f9f1e2fd.png)

It might be worth checking. You might try to configure something similar in `docker-compose.yml` file: 
![obraz](https://user-images.githubusercontent.com/12057520/90324453-5e9e0680-df6f-11ea-8a17-ea21c75de353.png)

**Comment by samcday** [comment]
Thanks for the fast reply! I tried some stuff similar to what you suggested already but didn't have much luck. I ended up finally giving up and just installing Ubuntu 16.04 natively to finally get a working Tizen Studio. Thanks anyway! :)
