### ISSUE TITLE
'Failed to get Tizen' error during installation

### ISSUE THREAD

**Issue by viniciusbaca** [kamildzi/Tizen4Docker#21]
Hi, I followed all the installation steps but in the end I got the error

`--2020-12-15 15:39:14--  http://download.tizen.org/sdk/Installer/tizen-studio_5.5/web-cli_Tizen_Studio_5.5_ubuntu-64.bin
Resolving download.tizen.org (download.tizen.org)... 52.79.222.238
Connecting to download.tizen.org (download.tizen.org)|52.79.222.238|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-15 15:39:15 ERROR 404: Not Found.`

 `[/opt/scripts/installTizenIDE.sh;ERR] Failed to get Tizen from: 
http://download.tizen.org/sdk/Installer/tizen-studio_5.5/web-cli_Tizen_Studio_5.5_ubuntu-64.bin`

` [./runTizen.sh] Terminating ...
non-network local connections being removed from access control list`

I'm currently using Arch Linux

**Comment by kamildzi** [comment]
Hello. 

It seems like you are trying to fetch an IDE version that doesn't exist yet. :smile: 
The latest version of Tizen Studio available is '4.0' and you are trying to download '5.5'. 
Please check and review your `TIZEN_VERSION` setting. You will find it in the `.env` configuration file. 

BTW. I think you may want to set version 5.5 to `TIZEN_TARGET` setting. If you are unsure of these values, please stay with defaults. You will be able to fetch any additional targets later, when the IDE is installed. 

PS. Please note that changing `TIZEN_VERSION` setting requires you to rebuild the docker image. If you are unsure how to do it, please refer to the last paragraph of the README.

**Comment by viniciusbaca** [comment]
Kamildzi, thanks for the quick response!

Yes, at first I've tried to download this unexisting version and should have mentioned it at the issue, sorry! 

But I removed all the repo and cloned again to retry a clean install but it still got the same error, are there any other dependencies in my environment that need to be erased? 

Thanks!

**Comment by kamildzi** [comment]
It is ok, no need to sorry. :stuck_out_tongue_winking_eye: 

You are probably left with old docker image. Wiping the repo is not enough to remove the docker image. 
You should check the last paragraph of the README file `IDE Upgrade / Reinstall process` (especially point no 4).

**Comment by viniciusbaca** [comment]
Thanks so much!!
 
Sorry, I didn't read carefully the reinstall instructions :( 
But now with the clean install everything is working properly :))))
