### ISSUE TITLE
Use Docker Compose v2 then fall back to `docker-compose`

### ISSUE THREAD

**Issue by jiriks74** [kamildzi/Tizen4Docker#32]
Hello,
I'll probably make a PR about this, if I'm able to, I'd just like to make you aware that many people aren't using `docker-compose` anymore and are using `docker compose` instead.

I currently don't have `docker-compose` installed and `checkdeps.sh` is saying that it didn't find it.

I think that the script should be updated to use `docker compose` and fallback to `docker-compose` if the first isn't found.

**Comment by kamildzi** [comment]
Hello, 
Thanks for the reminder! This is correct. `docker-compose` is not required any more. 
I will look and update the repository in spare time. 
Of course, feel free to contribute if you like. :)

**Comment by kamildzi** [comment]
Done - ed70a1290008ffb272e6ad0a6baeed67fc01388e / v0.9.15
